#!/usr/bin/env bash
# Script Proxmox LXC qBittorrent v5+ (Debian 12, tar.gz, volumes HD externo)
# Autor: Gustavo / Adaptado
# Licença: MIT

source <(curl -s https://raw.githubusercontent.com/tteck/Proxmox/main/misc/build.func)

function header_info {
clear
cat <<"EOF"
         ____  _ __  __                             __ 
  ____ _/ __ )(_) /_/ /_____  _____________  ____  / /_
 / __ `/ __  / / __/ __/ __ \/ ___/ ___/ _ \/ __ \/ __/
/ /_/ / /_/ / / /_/ /_/ /_/ / /  / /  /  __/ / / / /_  
\__, /_____/_/\__/\__/\____/_/  /_/   \___/_/ /_/\__/  
  /_/                                                  
EOF
}

header_info
echo -e "Loading..."
APP="qBittorrent"
var_disk="8"
var_cpu="2"
var_ram="2048"
var_os="debian"
var_version="12"
variables
color
catch_errors

# Configurações padrão do container
function default_settings() {
  CT_TYPE="1"
  PW=""
  CT_ID=$NEXTID
  HN=$NSAPP
  DISK_SIZE="$var_disk"
  CORE_COUNT="$var_cpu"
  RAM_SIZE="$var_ram"
  BRG="vmbr0"
  NET="dhcp"
  GATE=""
  APT_CACHER=""
  APT_CACHER_IP=""
  DISABLEIP6="no"
  MTU=""
  SD=""
  NS=""
  MAC=""
  VLAN=""
  SSH="no"
  VERB="no"
  echo_default
}

# Função para configurar volumes do HD externo
function setup_volumes() {
    echo -e "\nConfigurando volumes do HD externo..."
    mkdir -p /mnt/hdexterno/Downloads/incomplete
    mkdir -p /mnt/hdexterno/Downloads/complete
    chmod -R 777 /mnt/hdexterno/Downloads/incomplete /mnt/hdexterno/Downloads/complete

    echo "mp0: /mnt/hdexterno/Downloads/incomplete,mp=/mnt/incomplete" >> /etc/pve/lxc/$CT_ID.conf
    echo "mp1: /mnt/hdexterno/Downloads/complete,mp=/mnt/complete" >> /etc/pve/lxc/$CT_ID.conf
}

# Função de instalação de libtorrent-rasterbar >=2.0.10
function install_libtorrent() {
    echo -e "\nInstalando libtorrent-rasterbar >= 2.0.10..."
    apt update
    apt install -y build-essential pkg-config libboost-system-dev libboost-chrono-dev \
        libboost-random-dev libssl-dev curl
    cd /tmp
    wget https://github.com/arvidn/libtorrent/releases/download/libtorrent-2_0_10/libtorrent-rasterbar-2.0.10.tar.gz
    tar xzf libtorrent-rasterbar-2.0.10.tar.gz
    cd libtorrent-rasterbar-2.0.10
    ./configure
    make -j$(nproc)
    make install
    ldconfi
